<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link href='https://fonts.googleapis.com/css?family=Noto+Sans:400,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,800' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Audiowide' rel='stylesheet' type='text/css'>

<link href="/css/bootstrap.css" rel="stylesheet" />
<link href="/css/bootstrap-theme.css" rel="stylesheet" />
<link href="/css/bootstrap-defaults.css" rel="stylesheet" />
<link href="/css/layout.css" rel="stylesheet" />
<link href="/css/layout-theme.css" rel="stylesheet" />
<link href="/css/layout-theme.css" rel="stylesheet" />
<link href="/css/plugins/car/allsige-car.css" rel="stylesheet" />
<link href="/css/plugins/car/allsige-car-theme.css" rel="stylesheet" />
<link href="/css/animate.css" rel="stylesheet" />

<link href="/css/comp/menu.css" rel="stylesheet" />
<link href="/css/comp/main-box.css" rel="stylesheet" />
<link href="/css/comp/buttons.css" rel="stylesheet" />
<link href="/css/comp/dropdown.css" rel="stylesheet" />
<link href="/css/comp/table.css" rel="stylesheet" />
<link href="/css/comp/contextual.css" rel="stylesheet" />

<link href="/css/responsive/col-xs.css" rel="stylesheet" />


<script src="/js/jquery-3.1.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>


<script type="application/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-50467829-1', 'auto');
    ga('send', 'pageview');


    var allSIGE_Options = {
        showNavBar: true,
    };
    $('.dropdown-toggle').dropdown();
</script>