<header class="main-header">
    <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 text-center logomark-header main-sidebar">
        <a href="#">
            <h1></h1>
        </a>
        <a class="hidden-sm hidden-md hidden-lg responsive-box" href="#">
           <span class="fa fa-align-justify">
        </a>
    </div>
    <div class="main-container col-xs-12 col-sm-10 col-md-10 col-lg-10 header-options">
        <div class="row pull-right text-right">
            <ul>
                <li><span class="fa fa-bell-o"></span></li>
                <li><span class="fa fa-envelope-o"></span></li>
                <li><span class="fa fa-commenting-o"></span></li>
                <li class="hidden-xs"><span class="fa fa-thumb-tack"></span></li>
                <li class="menu-user">
                    <img src="/img/no-user-image.jpg" alt="User Picture" />
                    <span>Thiago Borges</span>
                </li>
                <li class="hidden-xs"><span class="fa fa-cogs"></li>
            </ul>
        </div>
    </div>
</header>
