<div class="main-sidebar col-xs-12 col-sm-12 col-md-12 col-lg-12 hidden-xs">
    <div class="row">
        <div class="col-md-12 menu-style menu-style-tool">
            <div class="input-group">
                <div class="input-group-addon"><span class="fa fa-search"></div>
                <input type="text" class="form-control" id="menu-search" placeholder="Buscar....">
            </div>
        </div>
        <div class="col-md-12 menu-style menu-style-tool">
            <div class="btn-group" role="group" aria-label="...">
                <button type="button" class="btn btn-gray"><span class="fa fa-list"></span></button>
                <button type="button" class="btn btn-gray"><span class="fa fa-backward"></span></button>
                <button type="button" class="btn btn-gray"><span class="fa fa-arrow-left"></span></button>
                <button type="button" class="btn btn-gray"><span class="fa fa-arrow-right"></span></button>
                <button type="button" class="btn btn-gray"><span class="fa fa-arrow-right"></span></button>
                <button type="button" class="btn btn-gray"><span class="fa fa-arrow-right"></span></button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 menu-itens-container">
                <ul class="menu-style">
                    <li class="current">
                        <a href="#">
                            <span class="icon fa fa-clone"></span>Programas<span class="new-item">Beta</span>
                        </a>
                        <ul class="menu-sub-panel">
                            <li><a href="#"><span class="icon fa fa-image"></span>SubCategoria 1</a></li>
                            <li><a href="#"><span class="icon fa fa-image"></span>SubCategoria 1</a></li>
                            <li><a href="#"><span class="icon fa fa-image"></span>SubCategoria 1</a></li>
                            <li><a href="#"><span class="icon fa fa-image"></span>SubCategoria 1</a></li>
                            <li><a href="#"><span class="icon fa fa-image"></span>SubCategoria 1</a></li>
                            <li><a href="#"><span class="icon fa fa-image"></span>SubCategoria 1</a></li>
                            <li><a href="#"><span class="icon fa fa-image"></span>SubCategoria 1</a></li>
                            <li><a href="#"><span class="icon fa fa-image"></span>SubCategoria 1</a></li>
                            <li><a href="#"><span class="icon fa fa-image"></span>SubCategoria 1</a></li>
                            <li><a href="#"><span class="icon fa fa-image"></span>SubCategoria 1</a></li>
                            <li><a href="#"><span class="icon fa fa-image"></span>SubCategoria 1</a></li>
                            <li><a href="#"><span class="icon fa fa-image"></span>SubCategoria 1</a></li>
                        </ul>
                    </li>
                    <li><a href="#"><span class="icon fa fa-code"></span>Sistemas</a></li>
                    <li><a href="#"><span class="icon fa fa-cogs"></span>Permissões</a></li>
                    <li><a href="#"><span class="icon fa fa-dashboard"></span>Usuários</a></li>
                    <li><a href="#"><span class="icon fa fa-envelope"></span>Configurações Gerais</a></li>
                    <li><a href="#"><span class="icon fa fa-female"></span>Configurações do Usuário</a></li>
                    <li><a href="#"><span class="icon fa fa-flash"></span>Forms</a></li>
                    <li><a href="#"><span class="icon fa fa-gavel"></span>Modals</a></li>
                    <li><a href="#"><span class="icon fa fa-image"></span>Data Table</a></li>
                    <li><a href="#"><span class="icon fa fa-image"></span>Opção Com o Nome Grande</a></li>
                    <li><a href="#"><span class="icon fa fa-image"></span>Data Table</a></li>
                    <li><a href="#"><span class="icon fa fa-image"></span>Data Table</a></li>
                    <li><a href="#"><span class="icon fa fa-gavel"></span>Modals</a></li>
                    <li><a href="#"><span class="icon fa fa-image"></span>Data Table</a></li>
                    <li><a href="#"><span class="icon fa fa-image"></span>Data Table</a></li>
                    <li><a href="#"><span class="icon fa fa-image"></span>Data Table</a></li>
                </ul>
                <div class="menu-style-modal">
                    
                </div>
            </div>
        </div>
    </div>
</div>